apiVersion: v1
kind: Namespace
metadata:
  name: gatekeeper-system
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gatekeeper
  namespace: gatekeeper-system
spec:
  interval: 10m
  chart:
    spec:
      chart: gatekeeper
      version: '>=3.15.0'
      sourceRef:
        kind: HelmRepository
        name: gatekeeper
        namespace: flux-system
      interval: 10m
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  values:
    replicas: 1
    audit:
      replicas: 1
