apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grafana-stack
  namespace: monitoring
spec:
  interval: 10m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '>=56.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
      interval: 10m
  install:
    crds: Create
    createNamespace: true
  upgrade:
    crds: CreateReplace
  valuesFrom:
    - kind: ConfigMap
      name: grafana-stack-values
      valuesKey: values.yaml
