# PostgreSQL for Keycloak
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
  labels:
    app: keycloak-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15-alpine
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER
          value: keycloak
        - name: POSTGRES_PASSWORD
          value: keycloak
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres-service
spec:
  selector:
    app: keycloak-postgres
  ports:
  - port: 5432
    targetPort: 5432
---
# Keycloak Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      initContainers:
      - name: wait-for-postgres
        image: busybox
        command: ['sh', '-c', 'until nc -z keycloak-postgres-service 5432; do echo waiting for postgres; sleep 2; done']
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:22.0
        args:
        - "start-dev"
        - "--import-realm"
        env:
        - name: KEYCLOAK_ADMIN
          value: admin
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: admin
        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://keycloak-postgres-service:5432/keycloak
        - name: KC_DB_USERNAME
          value: keycloak
        - name: KC_DB_PASSWORD
          value: keycloak
        - name: KC_HOSTNAME
          value: platform-auth.127.0.0.1.sslip.io
        - name: KC_HOSTNAME_STRICT
          value: "false"
        - name: KC_HTTP_ENABLED
          value: "true"
        - name: KC_HOSTNAME_STRICT_HTTPS
          value: "false"
        - name: KC_PROXY
          value: "edge"
        - name: KC_HTTP_CORS_ENABLED
          value: "true"
        - name: KC_HTTP_CORS_ORIGINS
          value: "*"
        - name: KC_HTTP_CORS_METHODS
          value: "GET,POST,PUT,DELETE,OPTIONS,HEAD"
        - name: KC_HTTP_CORS_HEADERS
          value: "*"
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /realms/master
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /realms/master
            port: 8080
          initialDelaySeconds: 90
          periodSeconds: 30
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: keycloak-realm
          mountPath: /opt/keycloak/data/import
          readOnly: true
      volumes:
      - name: keycloak-realm
        configMap:
          name: keycloak-realm-config
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
spec:
  selector:
    app: keycloak
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
# Ingress with nginx
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: keycloak-ingress
  annotations:
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS, HEAD"
    nginx.ingress.kubernetes.io/cors-allow-headers: "*"
spec:
  ingressClassName: nginx
  rules:
  - host: platform-auth.127.0.0.1.sslip.io
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: keycloak-service
            port:
              number: 8080
---
# Realm Config
apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-realm-config
data:
  teams-realm.json: |
    {
      "realm": "teams",
      "enabled": true,
      "sslRequired": "none",
      "registrationAllowed": false,
      "resetPasswordAllowed": true,
      "editUsernameAllowed": false,
      "bruteForceProtected": true,
      "clients": [
        {
          "clientId": "teams-ui",
          "name": "Teams UI",
          "description": "Angular Teams Management UI",
          "enabled": true,
          "clientAuthenticatorType": "client-secret",
          "redirectUris": [
            "http://platform-auth.127.0.0.1.sslip.io/*",
            "http://teams-ui.127.0.0.1.sslip.io/*",
            "http://localhost:4200/*"
          ],
          "webOrigins": [
            "http://platform-auth.127.0.0.1.sslip.io",
            "http://teams-ui.127.0.0.1.sslip.io",
            "http://localhost:4200"
          ],
          "publicClient": true,
          "protocol": "openid-connect",
          "attributes": {
            "post.logout.redirect.uris": "http://platform-auth.127.0.0.1.sslip.io/*##http://localhost:4200/*"
          }
        }
      ],
      "users": [
        {
          "username": "teamlead1",
          "enabled": true,
          "firstName": "Team",
          "lastName": "Lead",
          "email": "teamlead1@company.com",
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "password123",
              "temporary": false
            }
          ],
          "realmRoles": ["team-leader"]
        },
        {
          "username": "admin",
          "enabled": true,
          "firstName": "Admin",
          "lastName": "User",
          "email": "admin@company.com",
          "emailVerified": true,
          "credentials": [
            {
              "type": "password",
              "value": "admin123",
              "temporary": false
            }
          ],
          "realmRoles": ["admin", "team-leader"]
        }
      ],
      "roles": {
        "realm": [
          {
            "name": "team-leader",
            "description": "Can create and manage teams"
          },
          {
            "name": "admin",
            "description": "Full administrative access"
          }
        ]
      }
    }
