---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workshop-keycloak
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./workshop/teams-management/keycloak/flux-resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  wait: true
