---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: workshop-teams-operator
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./workshop/teams-management/teams-operator/flux-resources
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  wait: true
